version: '3'
services:
  database:
    image: mongo:latest
    container_name: corona-db

    volumes:
      - ~/.docker/mongodb/data/db/:/data/db/
      - ~/.docker/mongodb/data/log/:/var/log/mongodb/
      - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/

    env_file:
      - .env

    ports:
      - "27017:27017"
      
    restart: on-failure

    command: "mongod --auth"
